### ISSUE TITLE
The formula for Iab from Buhmann only works for a.energy = b.energy

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#13]
https://github.com/DavisThuillier/Ludwig.jl/blob/58fea54dfdad00e7f5e72489b2dddddb42e59dfc/src/integration.jl#L163

If a.energy and b.energy are close to each other but not exactly equal, one would need to use a modified formula which accounts for the small difference between them, similarly to what is done for electron_electron. 
But currently the energy contours are exactly the same for all bands (right?), so I imagine this if condition would only be satisfied when a.energy = b.energy anyway.

**Comment by DavisThuillier** [comment]
The energy contours are exactly the same for all the bands, so this condition is indeed satisfied only when a.energy = b.energy. However, before when the centroid of each patch was used for the representative momentum instead of how it is currently done, this check ensured that small energy differences would still be read as living within the same annulus. A much finer check/an annulus index check could now be used instead.
