### ISSUE TITLE
Convention for W is not consistent between orbital_weights and vertex_pk ?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#6]
https://github.com/DavisThuillier/Ludwig.jl/blob/e12cc78de30933ce5456febaf2c79c125132d167/scripts/materials/Sr2RuO4.jl#L94

The calculation of W in this function orbital_weights is not super transparent because it uses some unrelated elements of W as scratch space. I imagine this is to save time, although I am not sure if it is needed since mesh generation is probably pretty fast compared to integration?

Nonetheless, it is not obvious to me that the convention for eigenvectors used in this function is the same as the you use in vertex_pk for the momentum which is not on a patch, for which the second element of each eigenvector is chosen to always be positive.

**Comment by DavisThuillier** [comment]
This use of already allocated but non-referenced memory was important earlier when orbital_weights() was directly referenced in each integration loop, but this requirement is now deprecated since Fpk and Fpp are referenced instead without calls to orbital_weights(). Gauge disagreement fixed in iss6 branch and merged into develop.
